language: python
python:
  - 3.4
addons:
    code_climate:
        repo_token: 401f591ea50af4d9a3c91e77fbf7f4680b76fc66a0a79b33051088ab90374688
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python twittersent_analysis_test.py
  - coverage run twittersent_analysis_test.py
after_success:
  coveralls
